<?php

namespace App\Jobs;

use App\Models\Conversation;
use App\Models\Memory;
use App\Models\Contact;
use Illuminate\Bus\Batch;
use Illuminate\Support\Facades\Bus;
use Exception;
use Throwable;

/**
 * Extract Memory Job - Extract and store key memories from conversations
 *
 * This job analyzes a conversation to extract key memories and facts,
 * then chains them through vectorization and Pinecone storage.
 *
 * Queue: default
 * Timeout: 300 seconds (5 minutes)
 * Retries: 2 attempts
 */
class ExtractMemoryJob extends BaseJob
{
    /**
     * Queue assignment.
     *
     * @var string
     */
    public $queue = 'default';

    /**
     * Job timeout.
     *
     * @var int
     */
    public int $timeout = 300;

    /**
     * Number of retry attempts.
     *
     * @var int
     */
    public int $tries = 2;

    /**
     * Constructor.
     *
     * @param string $conversationId Conversation UUID
     */
    public function __construct(
        protected string $conversationId,
    ) {
        $this->idempotencyKey = "extract_memory:{$conversationId}";
    }

    /**
     * Execute the job - Extract memories from conversation.
     *
     * @return void
     * @throws Exception
     */
    public function handle(): void
    {
        $this->logJobStart([
            'conversation_id' => $this->conversationId,
        ]);

        try {
            // Check idempotency - prevent duplicate extraction
            if ($this->isProcessed()) {
                $this->logJobComplete([
                    'reason' => 'idempotent_skip',
                    'conversation_id' => $this->conversationId,
                ]);
                return;
            }

            // Fetch conversation with all messages
            $conversation = $this->safelyGetModel(Conversation::class, $this->conversationId);
            if (!$conversation) {
                throw new Exception("Conversation not found: {$this->conversationId}");
            }

            // Load messages for analysis
            $messages = $conversation->messages()
                ->orderBy('created_at', 'asc')
                ->get();

            if ($messages->isEmpty()) {
                $this->logJobComplete([
                    'reason' => 'no_messages',
                    'conversation_id' => $this->conversationId,
                ]);
                $this->markAsProcessed(['extracted_count' => 0]);
                return;
            }

            // Extract key memories from conversation
            $extractedMemories = $this->extractMemoriesFromConversation($messages, $conversation);

            if (empty($extractedMemories)) {
                $this->logJobComplete([
                    'reason' => 'no_extractable_memories',
                    'conversation_id' => $this->conversationId,
                ]);
                $this->markAsProcessed(['extracted_count' => 0]);
                return;
            }

            // Create Memory models for extracted content
            $jobChain = [];
            $extractedCount = 0;

            foreach ($extractedMemories as $memoryData) {
                try {
                    // Create memory record
                    $memory = Memory::create([
                        'contact_id' => $conversation->contact_id,
                        'conversation_id' => $this->conversationId,
                        'source' => 'conversation_extraction',
                        'type' => $memoryData['type'] ?? 'fact',
                        'title' => $memoryData['title'],
                        'content' => $memoryData['content'],
                        'metadata' => [
                            'extracted_at' => now()->toDateTimeString(),
                            'extraction_attempt' => $this->getCurrentAttempt(),
                        ],
                    ]);

                    // Chain vectorization and storage jobs
                    $jobChain[] = new VectorizeMemoryJob($memory->id, $memoryData['content']);
                    $jobChain[] = new SaveToPineconeJob(
                        $memory->id,
                        [], // Vector will be generated by VectorizeMemoryJob
                        ['source' => 'conversation']
                    );

                    $extractedCount++;

                } catch (Exception $e) {
                    \Log::error("Failed to create memory record", [
                        'conversation_id' => $this->conversationId,
                        'exception' => $e->getMessage(),
                    ]);
                    continue;
                }
            }

            // Dispatch job chain if any jobs created
            if (!empty($jobChain)) {
                try {
                    Bus::chain($jobChain)
                        ->catch(function (Batch $batch, Throwable $e) {
                            \Log::error("Memory extraction job chain failed", [
                                'conversation_id' => $this->conversationId,
                                'exception' => $e->getMessage(),
                            ]);
                        })
                        ->dispatch();
                } catch (Exception $e) {
                    \Log::error("Failed to dispatch memory job chain", [
                        'conversation_id' => $this->conversationId,
                        'exception' => $e->getMessage(),
                    ]);
                }
            }

            // Broadcast extraction event
            event(new \App\Events\MemoriesExtracted(
                $this->conversationId,
                $extractedCount
            ));

            // Mark as processed for idempotency
            $this->markAsProcessed([
                'extracted_count' => $extractedCount,
            ]);

            $this->logJobComplete([
                'conversation_id' => $this->conversationId,
                'extracted_count' => $extractedCount,
            ]);

        } catch (Exception $e) {
            $this->logJobFailure($e, [
                'conversation_id' => $this->conversationId,
                'attempt' => $this->getCurrentAttempt(),
            ]);

            throw $e;
        }
    }

    /**
     * Extract key memories from conversation messages.
     *
     * This is a simplified extraction logic. In production, this would use
     * NLP/LLM to identify important facts and entities.
     *
     * @param \Illuminate\Database\Eloquent\Collection $messages Collection of Message models
     * @param Conversation $conversation Conversation being analyzed
     * @return array Array of extracted memory data
     */
    protected function extractMemoriesFromConversation($messages, Conversation $conversation): array
    {
        $memories = [];

        // Simple extraction rules - in production, use ML/NLP
        $allContent = $messages->pluck('content')->implode(' ');

        // Extract mentioned contacts/entities
        $userMessages = $messages->where('sender_type', 'user');
        if ($userMessages->count() > 0) {
            $userMessage = $userMessages->first();
            $content = $userMessage->content;

            // Look for key patterns
            if (preg_match('/(?:my|i)\s+(?:am|\'m)\s+([^,.!?]+)/i', $content, $matches)) {
                $memories[] = [
                    'type' => 'fact',
                    'title' => 'User Background',
                    'content' => trim($matches[1]),
                ];
            }

            // Look for mentions of preferences
            if (preg_match('/(?:i|me)\s+(?:like|love|prefer|enjoy)\s+([^,.!?]+)/i', $content, $matches)) {
                $memories[] = [
                    'type' => 'preference',
                    'title' => 'User Preference',
                    'content' => trim($matches[1]),
                ];
            }

            // Look for concerns or issues
            if (preg_match('/(?:problem|issue|concern|worried|concerned)(?:\s+(?:about|with))?\s+([^,.!?]+)/i', $content, $matches)) {
                $memories[] = [
                    'type' => 'concern',
                    'title' => 'User Concern',
                    'content' => trim($matches[1]),
                ];
            }
        }

        // Extract general facts from all messages
        $sentences = preg_split('/[.!?]+/', $allContent, -1, PREG_SPLIT_NO_EMPTY);
        foreach (array_slice($sentences, 0, 3) as $sentence) { // Limit to first 3 sentences
            $cleaned = trim($sentence);
            if (strlen($cleaned) > 20 && strlen($cleaned) < 200) {
                $memories[] = [
                    'type' => 'fact',
                    'title' => 'Conversation Summary',
                    'content' => $cleaned,
                ];
            }
        }

        // Deduplicate similar memories
        return array_slice($memories, 0, 5); // Limit to 5 memories per conversation
    }

    /**
     * Extract idempotency data from job properties.
     *
     * @return array
     */
    protected function extractIdempotencyData(): array
    {
        return [
            'conversation_id' => $this->conversationId,
        ];
    }
}
